#collected by hand
column_dict={

#ATG-G22ATG
"JoshKaul":"G22ATGDKAU",
"EricToney":"G22ATGRTON",

#SOS-G22SOS
"DougLaFollette":"G22SOSDFOL",
"AmyLynnLoudenbeck":"G22SOSRLOU",
"NeilHarmon":"G22SOSLHAR",
"SharylR.McFarland":"G22SOSIMCF",

#TRE-G22TRE
"AaronRichardson":"G22TREDRIC",
"JohnS.Leiber":"G22TRERLEI",
"AndrewZuelke":"G22TRECZUE",

#GOV-G22GOV
"TonyEversSaraRodriguez":"G22GOVDEVE",
"TimMichelsRogerRoth":"G22GOVRMIC",
"JoanEllisBeglinger":"G22GOVIBEG",
"SethHaskin(write-in)":"G22GOVIHAS",

#USSenate-G22USS
"MandelaBarnes":"G22USSDBAR",
"RonJohnson":"G22USSRJOH",
"AdamPaul(write-in)":"G22USSIPAU"

}


#collected by script and edited as needed by hand
script_prod_copy_col_dict ={
    #CONG
    'Ann Roe': 'GCON01DROE',
 'Bryan Steil': 'GCON01RSTE',
 'Charles E. Barman': 'GCON01IBAR',
 'Mark Pocan': 'GCON02DPOC',
 'Erik Olsen': 'GCON02ROLS',
 'Douglas Alexander': 'GCON02IALE',
 'Brad Pfaff': 'GCON03DPFA',
 'Derrick Van Orden': 'GCON03RORD',
 'Gwen Moore': 'GCON04DMOO',
 'Tim Rogers': 'GCON04RROG',
 'Robert R. Raymond': 'GCON04IRAY',
 'Mike Van Someren': 'GCON05DSOM',
 'Scott Fitzgerald': 'GCON05RFIT',
 'Glenn Grothman': 'GCON06RGRO',
 'Tom Powell (write-in)': 'GCON06IPOW', 
 'Richard Dick Ausman': 'GCON07DAUS',
 'Tom Tiffany': 'GCON07RTIF',
 'Robbie Hoffman (write-in)': 'GCON08DHOF', 
 'Mike Gallagher': 'GCON08RGAL',
 'Paul David Boucher': 'GCON08IBOU',
 'Jacob J. VandenPlas': 'GCON08LVAN',
    'Julie Hancock (write-in)':'GCON08DHAN',
    

    
    #SU
    'Andrea Gage-Michaels': 'GSU01DGAG',
 'André Jacque': 'GSU01RJAC',
 'Tim  Carpenter': 'GSU03DCAR',
 'Angel Sanchez': 'GSU03RSAN',
 'Jessica  Katzenmeyer': 'GSU05DKAT',
 'Rob Hutton': 'GSU05RHUT',
 'Chris J. Larson': 'GSU07DLAR',
 'Peter Gilbert': 'GSU07RGIL',
 'Jarrod Schroeder (write-in)': 'GSU09DSCH',
 'Devin  LeMahieu': 'GSU09RLEM',
 'Steven J. Doelder': 'GSU11DDOE',
 'Steve  Nass': 'GSU11RNAS',
 'John  Jagler': 'GSU13RJAG',
 'Mark  Spreitzer': 'GSU15DSPR',
 'Mark Trofimchuck': 'GSU15RTRO',
 'Pat Skogen': 'GSU17DSKO',
 'Howard  Marklein': 'GSU17RMAR',
 'Kristin M Alfheim': 'GSU19DALF',
 'Rachael Cabral-Guevara': 'GSU19RCAB',
 'Van H. Wanggaard': 'GSU21RWAN',
 'Jesse James': 'GSU23RJAM',
 'Kelly Westlund': 'GSU25DWES',
 'Romaine Robert Quinn': 'GSU25RQUI',
 'Dianne H. Hesselbein': 'GSU27DHES',
 'Robert Relph': 'GSU27RREL',
 'Bob Look': 'GSU29DLOO',
 'Cory  Tomczyk': 'GSU29RTOM',
 'Jeff Smith': 'GSU31DSMI',
 'David  Estenson': 'GSU31REST',
 'Chris  Kapenga': 'GSU33RKAP',
    

    #SL
    'Roberta Thelen': 'GSL01DTHE',
 'Joel Kitchens': 'GSL01RKIT',
 'Renee Gasch': 'GSL02DGAS',
 'Shae  Sortwell': 'GSL02RSOR',
 'Ron  Tusler': 'GSL03RTUS',
 'Derek  Teague': 'GSL04DTEA',
 'David  Steffen': 'GSL04RSTE',
 'Joseph Van Deurzen': 'GSL05DDEU',
 'Joy Goeben': 'GSL05RGOE',
 'William J. Switalla': 'GSL06DSWI',
 'Peter  Schmidt': 'GSL06RSCH',
    #add in
    'Dean Neubert (write-in)':"GSL06RNEU",
    
 'Daniel Graan Riemer': 'GSL07DRIE',
 'Zachary  Marshall': 'GSL07RMAR',
 'Sylvia  Ortiz-Velez': 'GSL08DORT',
 'Marisabel  Cabrera': 'GSL09DCAB',
 'Ryan Michael Antczak': 'GSL09RANT',
 'Darrin Madison': 'GSL10DMAD',
 'Dora  Drake': 'GSL11DDRA',
 'LaKeshia N. Myers': 'GSL12DMYE',
 'Greg Canady': 'GSL12RCAN',
 'Sarah Harrison': 'GSL13DHAR',
 'Tom Michalski': 'GSL13RMIC',
 'Robyn Vining': 'GSL14DVIN',
 'Keva  Turner': 'GSL14RTUR',
 'Dave  Maxey': 'GSL15RMAX',
 'Kalan  Haywood': 'GSL16DHAY',
 'Supreme  Moore Omokunde': 'GSL17DOMO',
 'Abie Eisenbach': 'GSL17REIS',
 'Evan  Goyke': 'GSL18DGOY',
 'Ryan  Clancy': 'GSL19DCLA',
 'Christine M.  Sinicki': 'GSL20DSIN',
 'Scott Hermann': 'GSL20RHER',
 'Nathan M Jurowski': 'GSL21DJUR',
 'Jessie Rodriguez': 'GSL21RROD',
 'Matt Brown': 'GSL22DBRO',
 'Janel Brandtjen': 'GSL22RBRA',
 'Deb  Andraca': 'GSL23DAND',
 'Purnima  Nath': 'GSL23RNAT',
 'Bob  Tatterson': 'GSL24DTAT',
 'Dan  Knodl': 'GSL24RKNO',
 'Paul Tittl': 'GSL25RTIT',
 'Lisa Salgado': 'GSL26DSAL',
 'Terry A. Katsma': 'GSL26RKAT',
 'Amy  Binsfeld': 'GSL27RBIN',
 'Chet Gerlach': 'GSL27IGER',
 'Patty Schachtner': 'GSL28DSCH',
 'Gae Magnafici': 'GSL28RMAG',
 'Danielle  Johnson': 'GSL29DJOH',
 'Clint Moses': 'GSL29RMOS',
 'Sarah  Yacoub': 'GSL30DYAC',
 'Shannon  Zimmerman': 'GSL30RZIM',
 'Brienne  Brown': 'GSL31DBRO',
 'Ellen Schutt': 'GSL31RSCH',
 'Adam  Jaramillo': 'GSL32DJAR',
 'Tyler  August': 'GSL32RAUG',
 'Don  Vruwink': 'GSL33DVRU',
 'Scott Johnson': 'GSL33RJOH',
 'Eileen Daniel': 'GSL34DDAN',
 'Rob Swearingen': 'GSL34RSWE',
 'Calvin  Callahan': 'GSL35RCAL',
 'Todd Frederick': 'GSL35IFRE',
 'Ben Murray': 'GSL36DMUR',
 'Jeffrey Mursau': 'GSL36RMUR',
 'Maureen McCarville': 'GSL37DMCC',
 'William Penterman': 'GSL37RPEN',
 'Barbara Dittrich': 'GSL38RDIT',
 'Mark L Born': 'GSL39RBOR',
    #addin
    'Steve Rydzewski (write-in)':"GSL39RRYD",
 'Kevin Petersen': 'GSL40RPET',
 'Henry Fries': 'GSL40IFRI',
 'Alex Dallman': 'GSL41RDAL',
 'Theresa Valencia': 'GSL42DVAL',
 'Jon  Plumer': 'GSL42RPLU',
 'Jenna  Jacobson': 'GSL43DJAC',
 'Marisa  Voelkel': 'GSL43RVOE',
 'Sue Conley': 'GSL44DCON',
 'Spencer  Zimmerman': 'GSL44RZIM',
 'Clinton  Anderson': 'GSL45DAND',
 'Jeff Klett': 'GSL45RKLE',
 'Melissa  Ratcliff': 'GSL46DRAT',
 'Andrew McKinney': 'GSL46RMCK',
 'Jimmy  Anderson': 'GSL47DAND',
 'Lamonte Newsom': 'GSL47RNEW',
 'Samba  Baldeh': 'GSL48DBAL',
 'Lynne Parrott': 'GSL49DPAR',
 'Travis  Tranel': 'GSL49RTRA',
 'Michael  Leuth': 'GSL50DLEU',
 'Tony  Kurtz': 'GSL50RKUR',
 'Leah  Spicer': 'GSL51DSPI',
 'Todd Novak': 'GSL51RNOV',
 'Joe  Lavrenz': 'GSL52DLAV',
 "Jerry L. O'Connor": "GSL52RO'C",
 'Michael  Schraa': 'GSL53RSCH',
 'Lori Palmeri': 'GSL54DPAL',
 'Donnie Herman': 'GSL54RHER',
 'Stefanie A. Holt': 'GSL55DHOL',
 'Nate  Gustafson': 'GSL55RGUS',
 'Patrick Hayden': 'GSL56DHAY',
 'Dave Murphy': 'GSL56RMUR',
 'Lee  Snodgrass': 'GSL57DSNO',
 'Andrew Fox': 'GSL57RFOX',
 'Mary Ann  Rzeszutek': 'GSL58DRZE',
 'Rick  Gundrum': 'GSL58RGUN',
 'Ty Bodden': 'GSL59RBOD',
 'Daniel E. Larsen': 'GSL60DLAR',
 'Robert Brooks': 'GSL60RBRO',
 'Max Winkels': 'GSL61DWIN',
 'Amanda  Nedweski': 'GSL61RNED',
 'Anthony  Hammes': 'GSL62DHAM',
 'Robert Wittke': 'GSL62RWIT',
 'Joel Jacobsen (write-in)': 'GSL63DJAC',
 'Robin  Vos': 'GSL63RVOS',
    #Add in
    'Adam Steen (write-in)':"GSL63RSTE",
    
 'Tip McGuire': 'GSL64DMCG',
 'Ed Hibsch': 'GSL64RHIB',
 'Tod Ohnstad': 'GSL65DOHN',
 'Frank  Petrick': 'GSL65RPET',
 'Greta Neubauer': 'GSL66DNEU',
 'Carl  Hutton': 'GSL66LHUT',
 'Jason D. Bennett': 'GSL67DBEN',
 'Rob Summerfield': 'GSL67RSUM',
 'Nate Otto': 'GSL68DOTT',
 'Karen Hurd': 'GSL68RHUR',
 'Lisa Boero': 'GSL69DBOE',
 'Donna M. Rozar': 'GSL69RROZ',
 'Remy Gomez': 'GSL70DGOM',
 'Nancy Lynn VanderMeer': 'GSL70RVAN',
 'Katrina  Shankland': 'GSL71DSHA',
 'Scott Soik': 'GSL71RSOI',
 'Criste  Greening': 'GSL72DGRE',
 'Scott S. Krug': 'GSL72RKRU',
 'Laura R. Gapske': 'GSL73DGAP',
 'Angie Sapik': 'GSL73RSAP',
 'John Adams': 'GSL74DADA',
 'Chanz Green': 'GSL74RGRE',
 'David Armstrong': 'GSL75RARM',
 'Francesca  Hong': 'GSL76DHON',
 'Shelia  Stubbs': 'GSL77DSTU',
 'Lisa B. Subeck': 'GSL78DSUB',
 'Matt  Neuhaus': 'GSL78RNEU',
 'Alex  Joers': 'GSL79DJOE',
 'Victoria Fueger': 'GSL79RFUE',
 'Mike  Bare': 'GSL80DBAR',
 'Jacob D. Luginbuhl': 'GSL80RLUG',
 'David  Considine': 'GSL81DCON',
 'Shellie Benish': 'GSL81RBEN',
 'Deborah Davis': 'GSL82DDAV',
 'Chuck Wichgers': 'GSL82RWIC',
 'Zachary Roper (write-in)': 'GSL82IROP',
 'Nik Rettinger': 'GSL83RRET',
 'Chaz  Self': 'GSL83ISEL',
 'Lu Ann Bird': 'GSL84DBIR',
 'Bob  Donovan': 'GSL84RDON',
 'Kristin  Conway': 'GSL85DCON',
 'Patrick Snyder': 'GSL85RSNY',
 'John  Spiros': 'GSL86RSPI',
 'Elizabeth  Riley': 'GSL87DRIL',
 'James W. Edming': 'GSL87REDM',
 'Hannah Beauchamp-Pope': 'GSL88DBEA',
 'John Macco': 'GSL88RMAC',
 'Jane Benson': 'GSL89DBEN',
 'Elijah  Behnke': 'GSL89RBEH',
 'Kristina Shelton': 'GSL90DSHE',
 'Micah J. Behnke': 'GSL90RBEH',
 'Jodi Emerson': 'GSL91DEME',
 'Josh Stanley': 'GSL91RSTA',
 'Maria Bamonti': 'GSL92DBAM',
 'Treig E. Pronschinske': 'GSL92RPRO',
 'Alison H. Page': 'GSL93DPAG',
 'Warren L.  Petryk': 'GSL93RPET',
 'Steve  Doyle': 'GSL94DDOY',
 'Ryan Huebsch': 'GSL94RHUE',
 'Jill Billings': 'GSL95DBIL',
 'Chris  Woodard': 'GSL95RWOO',
 'Jayne M. Swiggum': 'GSL96DSWI',
 'Loren Oldenburg': 'GSL96ROLD',
 'Scott Allen': 'GSL97RALL',
 'Christina  Barry': 'GSL98DBAR',
 'Adam  Neylon': 'GSL98RNEY',
 'Alec Thomas Dahms': 'GSL99DDAH',
 'Cindi  Duchow': 'GSL99RDUC'
}
